### ISSUE TITLE
Hungarian support - not all sentences working

### ISSUE THREAD

**Issue by tanker11** [OHF-Voice/intents#1339]
Hello!

Appreciate the work on sentences and translation.
Giving some test to the voice I experience something not working properly.
Example:

Area alias added as "Emeleti fürdő"

The following sentence works: "emeleti fürdő árnyékoló zár"

But from the sentences there should be an alternative like: "emeleti fürdő redőny le".
This does NOT work. The answer is "Váratlan hiba történt".

What should be the cause of this not working?
I have tested several other intents from /intents/sentences/hu and majority of them throws an error instead of reacting properly.
What are the conditions to make it work?

**Comment by v1k70rk4** [comment]
@tanker11 Fixed in the next major HA version.
